name: Gigantic
main: com.github.unchama.gigantic.Gigantic
version: 0.1.0
description: Gigantic Seichi Server Plugin
softdepend: [PlaceholderAPI, LobbySwitch]

commands:
  achieve:
      description: This is achieve command.
      usage: /achieve give <playername> <id>
      aliases: [achiv,achievement,gachiv]
      default: op
      permission: gigantic.achieve
      permission-message: You don't have <permission>
  gacha:
      description: This is gacha command.
      usage: /<command> <help>
      aliases: [gc, seichigacha]
      default: op
      permission: gigantic.gacha
      permission-message: You don't have <permission>
  debug:
      description: This is debug command.
      usage: /<command> set
      aliases: [gigadebug,giganticdebug]
      default: op
      permission: gigantic.debug
      permission-message: You don't have <permission>
  mineboost:
      description: This is mineboost command.
      usage: /mb set <playername/all> <duration(tick)> <amplifier(double)> <id>
      aliases: [mb,gmb]
      default: op
      permission: gigantic.mineboost
      permission-message: You don't have <permission>
  stick:
      description: This is stick command
      aliases: [st,sti]
      default: true
      permission: gigantic.stick
      permission-message: You don't have <permission>
  fly:
      description: This is stick command
      usage: /<command> <finish/amount/endless>
      aliases: [giganticfly,gfly]
      default: true
      permission: gigantic.fly
      permission-message: You don't have <permission>
  growth:
      description: This is growth command
      aliases: [giganticgrowth,grw]
      default: true
      permission: gigantic.growth
      permission-message: You don't have <permission>
  presentbox:
      description: This is presentbox command.
      usage: /<command> send <playername/all>
      default: op
      permission: gigantic.presentbox
      permission-message: You don't have <permission>
  home:
      description: This is home command.
      usage: /<command> <set/tp> <amount>
      default: true
      permission: gigantic.home
      permission-message: You don't have <permission>
  genchant:
      description: This is GiganticEnchantment command.
      usage: /<command> <EnchantmentName> <Level>
      default: op
      permission: gigantic.genchant
      permission-message: You don't have <permission>
  listen:
      description: This is Listen command.
      usage: /<command> <donate/vote>
      default: op
      permission: gigantic.listen
      permission-message: You don't have <permission>
  takeover:
      description: This is Takeover command.
      usage: /<command> ranking
      default: op
      permission: gigantic.takeover
      permission-message: You don't have <permission>
  lastquit:
      description: This is Lastquit command.
      usage: /<command> <player>
      default: op
      permission: gigantic.lastquit
  halfguard:
      description: This is HaldGuard command.
      usage: /<command>
      default: op
      permission: gigantic.halfguard