name: Gigantic
main: com.github.unchama.gigantic.Gigantic
version: 0.1.0
description: Gigantic Seichi Server Plugin
softdepend: [PlaceholderAPI]



commands:
  gacha:
      description: This is gacha command.
      usage: /<command> <help>
      aliases: [gc, seichigacha]
      default: op
      permission: gigantic.gacha
      permission-message: You don't have <permission>
  debug:
      description: This is debug command.
      usage: /<command> set 
      aliases: [gigadebug,giganticdebug]
      default: op
      permission: gigantic.debug
      permission-message: You don't have <permission>
  mineboost:
      description: This is mineboost command.
      usage: /mb set <playername/all> <duration(tick)> <amplifier(double)> <id>
      aliases: [mb,gmb]
      default: op
      permission: gigantic.mineboost
      permission-message: You don't have <permission>
  stick:
      description: This is stick command
      aliases: stick
      default: op
      permission: gigantic.stick
      permission-message: You don't have <permission>
